version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-layer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-t3cf41dbxpj1"
s3_prefix = "test-layer"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
